### ISSUE TITLE
sync changes won't compile on thumbv6m

### ISSUE THREAD

**Issue by wez** [mvirkkunen/usb-device#2]
I was pretty excited to see the sync changes go in, but sad to see this:

```
$ cargo build --target thumbv6m-none-eabi
   Compiling usb-device v0.1.0 (file:///home/wez/wez-personal/usb-device)
error[E0599]: no method named `swap` found for type `core::sync::atomic::AtomicUsize` in the current scope
   --> src/device.rs:360:49
    |
360 |                 let addr = self.pending_address.swap(0, Ordering::SeqCst);
    |                                                 ^^^^

error[E0599]: no method named `compare_and_swap` found for type `core::sync::atomic::AtomicUsize` in the current scope
  --> src/utils/freezable_ref_cell.rs:32:23
   |
32 |         if self.state.compare_and_swap(
   |                       ^^^^^^^^^^^^^^^^

error[E0599]: no method named `compare_and_swap` found for type `core::sync::atomic::AtomicUsize` in the current scope
  --> src/utils/freezable_ref_cell.rs:49:23
   |
49 |         if self.state.compare_and_swap(
   |                       ^^^^^^^^^^^^^^^^

error[E0599]: no method named `compare_and_swap` found for type `core::sync::atomic::AtomicBool` in the current scope
  --> src/utils/atomic_mutex.rs:22:22
   |
22 |         if self.lock.compare_and_swap(false, true, Ordering::SeqCst) == false {
   |                      ^^^^^^^^^^^^^^^^

error: aborting due to 4 previous errors
```

**Comment by wez** [comment]
I wonder if you could draw from https://github.com/Rahix/shared-bus and how it handles pluggable mutexes?

**Comment by wez** [comment]
Just wanted to say: many thanks for making this crate and making it Sync; atsamd21 effectively requires interrupt driven USB and that was a hard blocker.  I'm super excited to see this enumerate and respond on the serial port :)

**Comment by mvirkkunen** [comment]
Aww... what a shame! I thought I could sidestep the issues with platform-specific synchronization by using what's in the standard library, but seems compare-and-swap is only available on platforms that truly support it in hardware, and it's not even mentioned in the docs as far as I can tell. Maybe they aren't used that often on embedded? (I even found a [code generation bug](https://bugs.llvm.org/show_bug.cgi?id=38828) in LLVM while implementing these.)

I'm still not 100% sure if it's this crate's job to require UsbBus implementations to be Sync, because that's not something many crates seem to require. However in the case of a shared bus I think letting it be thread-unsafe and requiring everybody to use a mutex would make it pretty inefficient. For instance, writing a 1kbyte packet into and endpoint would probably need to disable interrupts for the whole operation... which takes a pretty long time! Plus by requiring UsbBus to implement synchronization you can even read/write to multiple endpoints in parallel if need be.

I wonder if requiring a special type defined for mutexes like shared-bus would be better, or should the extra methods just be provided for AtomicBool/AtomicUsize by using weak linkage trickery?

**Comment by wez** [comment]
Regarding large transfers: the samd21 hardware allows registering an arbitrarily sized buffer and using DMA to manage the operation in hardware.  If you add support for this I think it would make the length of the critical sections shorter and less troublesome.

Regarding the synchronization itself: it seems like the usb device crate needs to allow for it but should probably be neutral in its implementation.  Using a trait for the locking primitive feels like it might be a reasonable solution, but I confess that I haven’t really studied the whole implementation to know for sure.

**Comment by mvirkkunen** [comment]
DMA would be really awesome, but from the chatter I've seen in relation to embedded-hal and friends, implementing a platform-agnostic interface for DMA is a pretty tough problem, and usb-device and and USB classes are going to be platform-agnostic. If somebody can figure out a way to do it though, I don't see why not.

I just committed c8ac5b0dd0a1cbefe355bfa2137b977a9041d5a1 which removes the single "swap" call in UsbDevice itself which wasn't really needed. The only remaining atomic swaps are now in the sync primitives in usb_device::utils. Strictly speaking those don't even have anything to do with USB, and they should probably be split off into separate crate(s). The only problem with using a trait I can think of is that it would have to thread through the entire implementation adding noise everywhere, to implement something that should really be implemented in the standard library (a basic compare-and-swap primitive).

**Comment by mvirkkunen** [comment]
I'm tempted to just split the "utils" bits into a new crate and add compare_and_swap support for thumbv6m using conditional compilation and ASM/intrinsics... then the end-users wouldn't even have to know.

**Comment by wez** [comment]
Yeah, I've been thinking something similar; factor those out into a compare and swap utility crate and deal with the portability concerns there.

**Comment by mvirkkunen** [comment]
The more I look into this the more hairy it gets. Cortex-M0 is really annoying because it doesn't have atomics, but it also has a non-privileged execution mode where you can't just disable interrupts to implement them with a critical section. I'm sure it's not the only chip that have this issue though.

I'm kind of leaning in favor of having a default implementation, but making it a weak function that can be overridden by somebody if they have some kind of operating system going that actually uses non-privileged mode.

**Comment by mvirkkunen** [comment]
963cc6be9123e5aad87b2c7bf4470631e9f903fe (in a branch for now) gets rids `AtomicMutex` entirely which is one step closer to no atomics required. There's now a lot of ugly `pub(crate)` due to the interaction between device.rs and device_standard_control.rs and I want to get rid of that too, but I'm focusing on removing `FreezableRefCell` next (what it does *ought* to be doable entirely at compile time, I just don't know how yet). Restructuring can wait for a moment.

**Comment by mvirkkunen** [comment]
fa85524ea5e7b70d030173ac2a5c87111bdacbdc gets rid of the last atomic operation in this crate, so it should no longer be a blocking issue. The responsibilities for synchronization are now entirely in the device-specific UsbBus (which is required to be Sync) and some are left to the user (UsbDevice and UsbClass are not required to be Sync anymore - I might change my mind again though)

**Comment by vhnatyk** [comment]
> I'm tempted to just split the "utils" bits into a new crate and add compare_and_swap support for thumbv6m using conditional compilation and ASM/intrinsics... then the end-users wouldn't even have to know.

hmm - looks like temptation passed over - looks like I need compare_and_swap for thumbv6m
